
cipher = "QSWWFCEBWREILVMCJVCHJWFUSVGUMQKSKSTUJSXRULAJYQLFSXCHPUHKWRVYMMGAJIGJZMKRZSWAYAHKWQCFZKBMMWEIUMVYFEENLIEJQLKXVQGQAHGIKPXPTIPCXVLMXXYUIMTLVFGJIWZPSQOYUBHHMQRILBPFWRAILIKCFSVYOXXALMPAZBAYUOGLJIKCARELVILGFKNSLABLYXJCJBXAZRKKLMDLGAPUJAMCYEPIXZTNZCVIKZBACMPNVZGCLYUYIATLVWOOXOECEENCTQHSKTCSCWTBKTCMKAXAMVKNPAVYFRGLJIGBXMTYNIEJKYPFZSXAJCRNFOKYHLAQYQVFOSTEJBHMTWEOIMVMFXGHKAHGLGCHKJXSFHGLJBHMVWVYXIGMYVCJYGLEGENCJBHFAHGNYMYYUXVBRBVMFXGHKMQGKXUUKIEJTCGGSMWBARICKQGQGQGNYQGEWPUYRVWQAREYJBXESRQAIIIFQMUUTWGAWTVHFBTQHIECWQVKWXJIUWYADEPXVAMGFIFUKIWCDMXYIGBRUEPVVCLCVMPUCTLMJXUIWQGEWRKILATLVAQLIGBLYEVNRKDQKXGARVHEJERBPQLYFEPWZMGRHVCWKQVCOLGHJXBCKMPNYMKCNSNOKQHLSVAQRZPPGXGCEQGTAWKVCMBLCSTQYMGBSZKHTQXKTIFXVLLCUVGNDMTLARICEIIYARVCEOMFSXYUJAMCYEPIXZTNZCVBZAPMJOUCEBACVMICKIEUGVNXKWHUZITYRNBJWPKEVIGGEEIYTIGZWWVYRTMFAPAYEKHBWHYCKPBLXSTGRBBMFJQLVFTKHPGJZFXJNENOVAUPAKJNEMLQSRFZZTMCJWGNKQGEKJQLRVBKSKGUIMGMJQCFCGVFSRIYUBHYXJGWKBACAQCAVATCKXJYKQVJGSMVLBAYUOGLJKTLSPUIDIGGHYNUKMMFWQDUJMWMFEUYTZXRUSFYNQMFFSTYXIKBXSTBFEMFWMPJLBLKSOGNYMBKSKGFFWDTAWWUCTRRZMUNVKALAUWYTIGZWYUYUNHPWXJCTIEPWEUIEALSULCMKWXTSHGWVVLMJWJCGWKCEFGXDMLQSKGMZVYYUIDIFSIFGXQMSCMRZIUYDMMFGHUWRVTJKSDYLAXBFIHUIQHSKPAZFZLCUYTCKGWCXIPXVZLRZISOVAMGGRKMYWPRGXGFCBACVMHZVZXLUIDYKEXCFEPCDIZCLLCNJJXCFQQXZNBCVJQLCMZGLMOUKMKCSWQHJIGBGRGNYIMQTIGHTPTLYIFNFAXAJIVFPKHLLEKHDIEGUMQOJQGDGVOUKQHLXVQGNQKCVQCARHBLW"
keyword = "SECURITY"

print("Decrypt ciphertext using the key={}".format(keyword))

def generate_key(string, k):
    k = list(k)
    if len(string) == len(k):
        return k
    else:
        for i in range(len(string) - len(k)):
            k.append(k[i % len(k)])
    return "".join(k)

def decrypt(cipher_text, k):
    orig_text = []
    for i in range(len(cipher_text)):
        x = (ord(cipher_text[i]) -
             ord(k[i]) + 26) % 26
        x += ord('A')
        orig_text.append(chr(x))
    return "".join(orig_text)

key = generate_key(cipher, keyword)
plaintext = decrypt(cipher, key)

print(plaintext)

def encrypt(string, k):
    cipher_text = []
    for i in range(len(string)):
        x = (ord(string[i]) + ord(k[i])) % 26
        x += ord('A')
        cipher_text.append(chr(x))
    return "".join(cipher_text)

ciphertext = encrypt(plaintext, key)
print(ciphertext)
